version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: socialNetwork_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=socialnetworkDB
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: socialnetworkDB
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
